name: test_task
description: Test project. There are 4 fields 2 of which are fixed, the others can be moved. Each field signed with a number corresponds to a field with a lowercase name. The functionality of the application checks if the numbered field corresponds to the field with a lowercase name.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
